<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\MesPlatform.Infrastructure\MesPlatform.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\MesPlatform.Application\MesPlatform.Application.csproj" />
    <ProjectReference Include="..\..\src\MesPlatform.Domain\MesPlatform.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>
</Project>
