<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MesPlatform.Application\MesPlatform.Application.csproj" />
    <ProjectReference Include="..\MesPlatform.Infrastructure\MesPlatform.Infrastructure.csproj" />
  </ItemGroup>
</Project>
